name: Build Android App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use the appropriate Node.js version

      - name: Install dependencies
        run: |
          npm install

      - name: Set executable permissions for gradlew
        run: |
          chmod +x android/gradlew

      - name: List Node Modules and Gradle Files
        run: |
          ls -la node_modules
          ls -la node_modules/@react-native
          cd android
          ls -la

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease --info

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk
