name: Build Android App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

          # Download and install Gradle
          wget https://services.gradle.org/distributions/gradle-7.6-bin.zip
          unzip gradle-7.6-bin.zip
          sudo mv gradle-7.6 /opt/gradle
          sudo chmod +x /opt/gradle/bin/gradle
          export PATH=$PATH:/opt/gradle/bin
          gradle --version

          # Install npm dependencies
          npm install

          # Ensure gradlew is executable
          chmod +x android/gradlew

          # Clean the build
          cd android
          ./gradlew clean

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk
