name: Build Android App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Set executable permissions for gradlew
        run: |
          chmod +x android/gradlew
      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease --stacktrace

      # - name: List APK Directory
      #   run: |
      #     cd android
      #     ls -la app/build/outputs/apk/release/
      #     ls -la app/build/outputs/apk/

      - name: List APK Directory After Build
        run: |
          cd android
          find . -name '*.apk'

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path:  android/app/build/outputs/apk/**/*.apk